[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.build]
cmds = ["npm install", "npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_VERSION = "20"
NPM_VERSION = "10"
NIXPACKS_NODE_VERSION = "20"
