[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["node server.js"]

[variables]
NIXPACKS_NODE_VERSION = "20"
NODE_ENV = "development"
PORT = "3001"
NPM_CONFIG_PRODUCTION = "false"
